// <auto-generated />
using System;
using ClimbingApplication.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClimbingApplication.Migrations
{
    [DbContext(typeof(EFContextcs))]
    [Migration("20250830104022_FelhasznalonevHozzadasa")]
    partial class FelhasznalonevHozzadasa
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("ClimbingApplication.Models.Falak", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FalmaszohelyID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("kep")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("letrehozva")
                        .HasColumnType("TEXT");

                    b.Property<string>("nev")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("FalmaszohelyID");

                    b.ToTable("Falak");
                });

            modelBuilder.Entity("ClimbingApplication.Models.FalmaszoHelyek", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FelhasznalokID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("cim")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("honlap")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("koordinata")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("leiras")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("orszag")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("FelhasznalokID");

                    b.ToTable("FalmaszoHelyek");
                });

            modelBuilder.Entity("ClimbingApplication.Models.Felhasznalok", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("felhasznaloNev")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("jelszo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("keresztNev")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("rang")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("szuletesiIdo")
                        .HasColumnType("TEXT");

                    b.Property<string>("telefonszam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("vezetekNev")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Felhasznalok");
                });

            modelBuilder.Entity("ClimbingApplication.Models.Hozzaszolasok", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FelhasznaloID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UtakID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("hozzaszolas")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("FelhasznaloID");

                    b.HasIndex("UtakID");

                    b.ToTable("Hozzaszolasok");
                });

            modelBuilder.Entity("ClimbingApplication.Models.Utak", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FalID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FelhasznaloID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("kep")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("leiras")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("letrehozva")
                        .HasColumnType("TEXT");

                    b.Property<string>("nehezseg")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("nev")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("FalID");

                    b.HasIndex("FelhasznaloID");

                    b.ToTable("Utak");
                });

            modelBuilder.Entity("ClimbingApplication.Models.Valaszok", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FelhasznaloID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HozzaszolasID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("valasz")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("FelhasznaloID");

                    b.HasIndex("HozzaszolasID");

                    b.ToTable("Valaszok");
                });

            modelBuilder.Entity("ClimbingApplication.Models.Falak", b =>
                {
                    b.HasOne("ClimbingApplication.Models.FalmaszoHelyek", "Falhelye")
                        .WithMany()
                        .HasForeignKey("FalmaszohelyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Falhelye");
                });

            modelBuilder.Entity("ClimbingApplication.Models.FalmaszoHelyek", b =>
                {
                    b.HasOne("ClimbingApplication.Models.Felhasznalok", "Hozzaado")
                        .WithMany()
                        .HasForeignKey("FelhasznalokID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hozzaado");
                });

            modelBuilder.Entity("ClimbingApplication.Models.Hozzaszolasok", b =>
                {
                    b.HasOne("ClimbingApplication.Models.Felhasznalok", "UtHozzaszolo")
                        .WithMany()
                        .HasForeignKey("FelhasznaloID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClimbingApplication.Models.Utak", "UtHozzaszolas")
                        .WithMany("Hozzaszolasoks")
                        .HasForeignKey("UtakID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UtHozzaszolas");

                    b.Navigation("UtHozzaszolo");
                });

            modelBuilder.Entity("ClimbingApplication.Models.Utak", b =>
                {
                    b.HasOne("ClimbingApplication.Models.Falak", "Falonut")
                        .WithMany()
                        .HasForeignKey("FalID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClimbingApplication.Models.Felhasznalok", "UtLetrehozo")
                        .WithMany()
                        .HasForeignKey("FelhasznaloID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Falonut");

                    b.Navigation("UtLetrehozo");
                });

            modelBuilder.Entity("ClimbingApplication.Models.Valaszok", b =>
                {
                    b.HasOne("ClimbingApplication.Models.Felhasznalok", "Valasziro")
                        .WithMany()
                        .HasForeignKey("FelhasznaloID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClimbingApplication.Models.Hozzaszolasok", "Valasz")
                        .WithMany("Valaszok")
                        .HasForeignKey("HozzaszolasID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Valasz");

                    b.Navigation("Valasziro");
                });

            modelBuilder.Entity("ClimbingApplication.Models.Hozzaszolasok", b =>
                {
                    b.Navigation("Valaszok");
                });

            modelBuilder.Entity("ClimbingApplication.Models.Utak", b =>
                {
                    b.Navigation("Hozzaszolasoks");
                });
#pragma warning restore 612, 618
        }
    }
}
