// <auto-generated />
using System;
using ClimbingApplication.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClimbingApplication.Migrations
{
    [DbContext(typeof(EFContextcs))]
    partial class EFContextcsModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("ClimbingApplication.Models.Falak", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FalID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("kep")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("letrehozva")
                        .HasColumnType("TEXT");

                    b.Property<string>("nev")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("FalID");

                    b.ToTable("Falak");
                });

            modelBuilder.Entity("ClimbingApplication.Models.FalmaszoHelyek", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FalID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("cim")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("honlap")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("koordinata")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("leiras")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("orszag")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("FalID");

                    b.ToTable("FalmaszoHelyek");
                });

            modelBuilder.Entity("ClimbingApplication.Models.Felhasznalok", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("HelyID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HozzaszolasokID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ValaszokID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ValaszoloID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("jelszo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("keresztNev")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("rang")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("szuletesiIdo")
                        .HasColumnType("TEXT");

                    b.Property<string>("telefonszam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("vezetekNev")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("HelyID");

                    b.HasIndex("HozzaszolasokID");

                    b.HasIndex("ValaszoloID");

                    b.ToTable("Felhasznalok");
                });

            modelBuilder.Entity("ClimbingApplication.Models.Hozzaszolasok", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ValaszID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ValaszokID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("hozzaszolas")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("ValaszID");

                    b.ToTable("Hozzaszolasok");
                });

            modelBuilder.Entity("ClimbingApplication.Models.Utak", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("HozzaszolasokID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("kep")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("leiras")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("letrehozva")
                        .HasColumnType("TEXT");

                    b.Property<string>("nehezseg")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("nev")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("HozzaszolasokID");

                    b.ToTable("Utak");
                });

            modelBuilder.Entity("ClimbingApplication.Models.Valaszok", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("valasz")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Valaszok");
                });

            modelBuilder.Entity("ClimbingApplication.Models.Falak", b =>
                {
                    b.HasOne("ClimbingApplication.Models.Utak", "Falonut")
                        .WithMany()
                        .HasForeignKey("FalID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Falonut");
                });

            modelBuilder.Entity("ClimbingApplication.Models.FalmaszoHelyek", b =>
                {
                    b.HasOne("ClimbingApplication.Models.Falak", "Falnev")
                        .WithMany()
                        .HasForeignKey("FalID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Falnev");
                });

            modelBuilder.Entity("ClimbingApplication.Models.Felhasznalok", b =>
                {
                    b.HasOne("ClimbingApplication.Models.FalmaszoHelyek", "HelyHozzaado")
                        .WithMany()
                        .HasForeignKey("HelyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClimbingApplication.Models.Hozzaszolasok", "Hozzaszolo")
                        .WithMany()
                        .HasForeignKey("HozzaszolasokID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClimbingApplication.Models.Hozzaszolasok", "Valaszolo")
                        .WithMany()
                        .HasForeignKey("ValaszoloID");

                    b.Navigation("HelyHozzaado");

                    b.Navigation("Hozzaszolo");

                    b.Navigation("Valaszolo");
                });

            modelBuilder.Entity("ClimbingApplication.Models.Hozzaszolasok", b =>
                {
                    b.HasOne("ClimbingApplication.Models.Hozzaszolasok", "Valasz")
                        .WithMany()
                        .HasForeignKey("ValaszID");

                    b.Navigation("Valasz");
                });

            modelBuilder.Entity("ClimbingApplication.Models.Utak", b =>
                {
                    b.HasOne("ClimbingApplication.Models.Hozzaszolasok", "Hozzaszolas")
                        .WithMany()
                        .HasForeignKey("HozzaszolasokID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hozzaszolas");
                });
#pragma warning restore 612, 618
        }
    }
}
